version: "2.1"
services:
  rabbitmq:
    image: rabbitmq:3.10.7-management
    hostname: rabbitmq
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=$RABBITMQ_USER
      - RABBITMQ_DEFAULT_PASS=$RABBITMQ_PASS
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit disk_free_limit 2147483648 #for rabbit not to crash mem 2 Gbit
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
      - ./init/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./init/definitions.json:/etc/rabbitmq/definitions.json:ro
    ports:
      - "5672:5672"
      - "15672:15672"
#    networks:
#      - my_network

#  elasticsearch:
#    image: elasticsearch:7.17.19
#    container_name: elasticsearch
#    environment:
#      - xpack.security.enabled=false
#      - discovery.type=single-node
#    ulimits:
#      memlock:
#        soft: -1
#        hard: -1
#      nofile:
#        soft: 65536
#        hard: 65536
#    cap_add:
#      - IPC_LOCK
#    volumes:
#      - ./elasticsearch-data:/usr/share/elasticsearch/data
#    ports:
#      - "9200:9200"
#      - "9300:9300"
#
#  kibana:
#    container_name: kibana
#    image: kibana:7.17.19
#    environment:
#      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
#    volumes:
#      - ./kibana-data:/usr/share/kibana/data
#    ports:
#      - "5601:5601"
#    depends_on:
#      - elasticsearch
#
#  filebeat:
#    container_name: filebeat
#    image: docker.elastic.co/beats/filebeat:7.17.19
#    volumes:
#      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
##      - /var/lib/docker/containers:/var/lib/docker/containers:ro
##      - /var/run/docker.sock:/var/run/docker.sock:ro
#    depends_on:
#      - elasticsearch
#    networks:
#      - my_network

#  logstash:
#    container_name: logstash
#    build:
#      context: ./logstash
#    volumes:
#      - ./logstash/config:/usr/share/logstash/config
#      - ./logstash/pipeline:/usr/share/logstash/pipeline
#    ports:
#      - "5044:5044"
#    depends_on:
#      - elasticsearch

#  website-parser:
#    image: maven-image
#    depends_on:
#      - rabbitmq
#      - elasticsearch
#    hostname: website-parser
#    container_name: website-parser
##    build:
##      context: ../
##      dockerfile: ./deployment/Dockerfile
##    command: ["/bin/bash", "-c", "./maven_compile.sh"]
#    networks:
#      - my_network



#networks:
#  my_network:
#    name: my_network
#    driver: bridge